### ISSUE TITLE
When upload the code?

### ISSUE THREAD

**Issue by sgtojd** [Ranchosky/SFRNet#8]
The work is very inspiring. And I wonder when will the core codes released.

**Comment by Morningstaripfy** [comment]
configs/obb/oriented_rcnn/sfr_faster_rcnn_orpn_r50_fpn_1x_fair1m.py

mmdet/models/roi_heads/bbox_heads/obb/sfr_obb_convfc_bbox_head.py

**Comment by sgtojd** [comment]
Thanks a lot!
